---
title: "2023 Analysis GFP vs. WT"
author: "Michelle Bang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Using tidyverse
library(tidyverse)
```

```{r}
new_df <- read.table(file = "2023datanew.tsv",
                              header = TRUE,
                              sep = '\t', na.strings = c("", " ", NA))
```


```{r}
new_df <- new_df %>%
  mutate(category = if_else(is.na(category), "unknown", category))

new_df %>%
  group_by(category) %>%
  summarize(count = n())
```

```{r}
# separating the data into categories
vc_high <- new_df[new_df$category == "vegetative_cell_high",]
sc_high <- new_df[new_df$category == "sperm_cell_high",]
vc <- new_df[new_df$category == "vegetative_cell",]
sc <- new_df[new_df$category == "sperm_cell",]
so <- new_df[new_df$category == "seedling_only",]
so_star <- new_df[new_df$category == "seedling_only*",]

# unknown category
unknown <- new_df[new_df$category == "unknown",]
```

# Analysis on Vegetative Cell High
```{r}

# Using quasi binomial log model

veg_mod <- glm(cbind(number_of_GFP_kernels, number_of_WT_kernels) ~
                                as.factor(allele),
                              data = vc_high,
                              family = quasibinomial(link = "logit"))
print(veg_mod)

S = vcov(veg_mod)

raw_p = coef(summary(veg_mod))[1,4]
beta_list = coef(summary(veg_mod))[1,1]
est_coef = (exp(beta_list)/(1 + exp(beta_list)))
low_int = exp(beta_list - qnorm(.975)*coef(summary(veg_mod))[1,2])/(1+exp(beta_list - qnorm(.975)*coef(summary(veg_mod))[1,2]))
up_int = exp(beta_list + qnorm(.975)*coef(summary(veg_mod))[1,2])/(1+exp(beta_list + qnorm(.975)*coef(summary(veg_mod))[1,2]))

for (i in 2:nrow(coef(summary(veg_mod)))){ # Starting at 2 because we already collected the first one...
  beta = coef(summary(veg_mod))[1,1] + coef(summary(veg_mod))[i,1] # Intercept + Allele coefficient 
  sigma = sqrt(sum(S[c(1,i),c(1,i)])) # Sigma from variance matrix
  raw_p = c(raw_p, 2*(1-pnorm(abs(beta/sigma)))) # Raw p calculated using z normal distribution
  beta_list = c(beta_list, beta)
  est_coef = c(est_coef, (exp(beta)/(1+exp(beta))))
  low_int = c(low_int, exp(beta-qnorm(.975)*sigma)/(1+exp(beta-qnorm(.975)*sigma)))
  up_int = c(up_int, exp(beta+qnorm(.975)*sigma)/(1+exp(beta+qnorm(.975)*sigma)))
  
}

adjusted_p = p.adjust(raw_p, method = "BH")

Alleles = sort(unique(vc_high$allele))

names(raw_p) = sort(unique(vc_high$allele)) # Names is name or row, unique only picks unique value from dataset
names(beta_list) = sort(unique(vc_high$allele))
names(est_coef) = sort(unique(vc_high$allele))
names(Alleles) = sort(unique(vc_high$allele))
names(adjusted_p) = sort(unique(vc_high$allele))
names(low_int) = sort(unique(vc_high$allele))
names(up_int) = sort(unique(vc_high$allele))

nanalysis_summary_vc = data.frame(allele = Alleles, logit_of_percentage = beta_list, estimated_transmission_percentage = est_coef, lower_confidence_interval = low_int, upper_confidence_interval = up_int, raw_p_value = raw_p, adj_p_value = adjusted_p)

nanalysis_summary_vc$expression_category = "Vegetative Cell High"

```

# Analysis on Vegetative Cell
```{r}

# Using quasi binomial log model

veg_mod <- glm(cbind(number_of_GFP_kernels, number_of_WT_kernels) ~
                                as.factor(allele),
                              data = vc,
                              family = quasibinomial(link = "logit"))
print(veg_mod)

S = vcov(veg_mod)

raw_p = coef(summary(veg_mod))[1,4]
beta_list = coef(summary(veg_mod))[1,1]
est_coef = (exp(beta_list)/(1 + exp(beta_list)))
low_int = exp(beta_list - qnorm(.975)*coef(summary(veg_mod))[1,2])/(1+exp(beta_list - qnorm(.975)*coef(summary(veg_mod))[1,2]))
up_int = exp(beta_list + qnorm(.975)*coef(summary(veg_mod))[1,2])/(1+exp(beta_list + qnorm(.975)*coef(summary(veg_mod))[1,2]))

for (i in 2:nrow(coef(summary(veg_mod)))){ # Starting at 2 because we already collected the first one...
  beta = coef(summary(veg_mod))[1,1] + coef(summary(veg_mod))[i,1] # Intercept + Allele coefficient 
  sigma = sqrt(sum(S[c(1,i),c(1,i)])) # Sigma from variance matrix
  raw_p = c(raw_p, 2*(1-pnorm(abs(beta/sigma)))) # Raw p calculated using z normal distribution
  beta_list = c(beta_list, beta)
  est_coef = c(est_coef, (exp(beta)/(1+exp(beta))))
  low_int = c(low_int, exp(beta-qnorm(.975)*sigma)/(1+exp(beta-qnorm(.975)*sigma)))
  up_int = c(up_int, exp(beta+qnorm(.975)*sigma)/(1+exp(beta+qnorm(.975)*sigma)))
  
}

adjusted_p = p.adjust(raw_p, method = "BH")

Alleles = sort(unique(vc$allele))

names(raw_p) = sort(unique(vc$allele)) # Names is name or row, unique only picks unique value from dataset
names(beta_list) = sort(unique(vc$allele))
names(est_coef) = sort(unique(vc$allele))
names(Alleles) = sort(unique(vc$allele))
names(adjusted_p) = sort(unique(vc$allele))
names(low_int) = sort(unique(vc$allele))
names(up_int) = sort(unique(vc$allele))

nanalysis_summary_vc_n = data.frame(allele = Alleles, logit_of_percentage = beta_list, estimated_transmission_percentage = est_coef, lower_confidence_interval = low_int, upper_confidence_interval = up_int, raw_p_value = raw_p, adj_p_value = adjusted_p)

nanalysis_summary_vc_n$expression_category = "Vegetative Cell"

```


# Analysis on Sperm Cell 

```{r}
# Using quasi binomial log model

sperm_mod <- glm(cbind(number_of_GFP_kernels, number_of_WT_kernels) ~
                                as.factor(allele),
                              data = sc,
                              family = quasibinomial(link = "logit"))
print(sperm_mod)

S = vcov(sperm_mod)

raw_p = coef(summary(sperm_mod))[1,4]
beta_list = coef(summary(sperm_mod))[1,1]
est_coef = (exp(beta_list)/(1 + exp(beta_list)))
low_int = exp(beta_list - qnorm(.975)*coef(summary(sperm_mod))[1,2])/(1+exp(beta_list - qnorm(.975)*coef(summary(sperm_mod))[1,2]))
up_int = exp(beta_list + qnorm(.975)*coef(summary(sperm_mod))[1,2])/(1+exp(beta_list + qnorm(.975)*coef(summary(sperm_mod))[1,2]))

for (i in 2:nrow(coef(summary(sperm_mod)))){ # Starting at 2 because we already collected the first one...
  beta = coef(summary(sperm_mod))[1,1] + coef(summary(sperm_mod))[i,1] # Intercept + Allele coefficient 
  sigma = sqrt(sum(S[c(1,i),c(1,i)])) # Sigma from variance matrix
  raw_p = c(raw_p, 2*(1-pnorm(abs(beta/sigma)))) # Raw p calculated using z normal distribution
  beta_list = c(beta_list, beta)
  est_coef = c(est_coef, (exp(beta)/(1+exp(beta))))
  low_int = c(low_int, exp(beta-qnorm(.975)*sigma)/(1+exp(beta-qnorm(.975)*sigma)))
  up_int = c(up_int, exp(beta+qnorm(.975)*sigma)/(1+exp(beta+qnorm(.975)*sigma)))
  
}

adjusted_p = p.adjust(raw_p, method = "BH")

Alleles = sort(unique(sc$allele))

names(raw_p) = sort(unique(sc$allele)) # Names is name or row, unique only picks unique value from dataset
names(beta_list) = sort(unique(sc$allele))
names(est_coef) = sort(unique(sc$allele))
names(Alleles) = sort(unique(sc$allele))
names(adjusted_p) = sort(unique(sc$allele))
names(low_int) = sort(unique(sc$allele))
names(up_int) = sort(unique(sc$allele))

nanalysis_summary_sc_n = data.frame(allele = Alleles, logit_of_percentage = beta_list, estimated_transmission_percentage = est_coef, lower_confidence_interval = low_int, upper_confidence_interval = up_int, raw_p_value = raw_p, adj_p_value = adjusted_p)

nanalysis_summary_sc_n$expression_category = "Sperm Cell"

```

# Analysis on Sperm Cell High

```{r}
# Using quasi binomial log model

sperm_mod <- glm(cbind(number_of_GFP_kernels, number_of_WT_kernels) ~
                                as.factor(allele),
                              data = sc_high,
                              family = quasibinomial(link = "logit"))
print(sperm_mod)

S = vcov(sperm_mod)

raw_p = coef(summary(sperm_mod))[1,4]
beta_list = coef(summary(sperm_mod))[1,1]
est_coef = (exp(beta_list)/(1 + exp(beta_list)))
low_int = exp(beta_list - qnorm(.975)*coef(summary(sperm_mod))[1,2])/(1+exp(beta_list - qnorm(.975)*coef(summary(sperm_mod))[1,2]))
up_int = exp(beta_list + qnorm(.975)*coef(summary(sperm_mod))[1,2])/(1+exp(beta_list + qnorm(.975)*coef(summary(sperm_mod))[1,2]))

for (i in 2:nrow(coef(summary(sperm_mod)))){ # Starting at 2 because we already collected the first one...
  beta = coef(summary(sperm_mod))[1,1] + coef(summary(sperm_mod))[i,1] # Intercept + Allele coefficient 
  sigma = sqrt(sum(S[c(1,i),c(1,i)])) # Sigma from variance matrix
  raw_p = c(raw_p, 2*(1-pnorm(abs(beta/sigma)))) # Raw p calculated using z normal distribution
  beta_list = c(beta_list, beta)
  est_coef = c(est_coef, (exp(beta)/(1+exp(beta))))
  low_int = c(low_int, exp(beta-qnorm(.975)*sigma)/(1+exp(beta-qnorm(.975)*sigma)))
  up_int = c(up_int, exp(beta+qnorm(.975)*sigma)/(1+exp(beta+qnorm(.975)*sigma)))
  
}

adjusted_p = p.adjust(raw_p, method = "BH")

Alleles = sort(unique(sc_high$allele))

names(raw_p) = sort(unique(sc_high$allele)) # Names is name or row, unique only picks unique value from dataset
names(beta_list) = sort(unique(sc_high$allele))
names(est_coef) = sort(unique(sc_high$allele))
names(Alleles) = sort(unique(sc_high$allele))
names(adjusted_p) = sort(unique(sc_high$allele))
names(low_int) = sort(unique(sc_high$allele))
names(up_int) = sort(unique(sc_high$allele))

nanalysis_summary_sc = data.frame(allele = Alleles, logit_of_percentage = beta_list, estimated_transmission_percentage = est_coef, lower_confidence_interval = low_int, upper_confidence_interval = up_int, raw_p_value = raw_p, adj_p_value = adjusted_p)

nanalysis_summary_sc$expression_category = "Sperm Cell High"

```

# Analysis on seedling only 
```{r}

# Using quasi binomial log model

seed_mod <- glm(cbind(number_of_GFP_kernels, number_of_WT_kernels) ~
                                as.factor(allele),
                              data = so,
                              family = quasibinomial(link = "logit"))
print(seed_mod)

S = vcov(seed_mod)

raw_p = coef(summary(seed_mod))[1,4]
beta_list = coef(summary(seed_mod))[1,1]
est_coef = (exp(beta_list)/(1 + exp(beta_list)))
low_int = exp(beta_list - qnorm(.975)*coef(summary(seed_mod))[1,2])/(1+exp(beta_list - qnorm(.975)*coef(summary(seed_mod))[1,2]))
up_int = exp(beta_list + qnorm(.975)*coef(summary(seed_mod))[1,2])/(1+exp(beta_list + qnorm(.975)*coef(summary(seed_mod))[1,2]))

for (i in 2:nrow(coef(summary(seed_mod)))){ # Starting at 2 because we already collected the first one...
  beta = coef(summary(seed_mod))[1,1] + coef(summary(seed_mod))[i,1] # Intercept + Allele coefficient 
  sigma = sqrt(sum(S[c(1,i),c(1,i)])) # Sigma from variance matrix
  raw_p = c(raw_p, 2*(1-pnorm(abs(beta/sigma)))) # Raw p calculated using z normal distribution
  beta_list = c(beta_list, beta)
  est_coef = c(est_coef, (exp(beta)/(1+exp(beta))))
  low_int = c(low_int, exp(beta-qnorm(.975)*sigma)/(1+exp(beta-qnorm(.975)*sigma)))
  up_int = c(up_int, exp(beta+qnorm(.975)*sigma)/(1+exp(beta+qnorm(.975)*sigma)))
  
}

adjusted_p = p.adjust(raw_p, method = "BH")

Alleles = sort(unique(so$allele))

names(raw_p) = sort(unique(so$allele)) # Names is name or row, unique only picks unique value from dataset
names(beta_list) = sort(unique(so$allele))
names(est_coef) = sort(unique(so$allele))
names(Alleles) = sort(unique(so$allele))
names(adjusted_p) = sort(unique(so$allele))
names(low_int) = sort(unique(so$allele))
names(up_int) = sort(unique(so$allele))

nanalysis_summary_seed = data.frame(allele = Alleles, logit_of_percentage = beta_list, estimated_transmission_percentage = est_coef, lower_confidence_interval = low_int, upper_confidence_interval = up_int, raw_p_value = raw_p, adj_p_value = adjusted_p)

nanalysis_summary_seed$expression_category = "Seedling Only"
```
# Analysis on seedling only* ... DOES NOT WORK! ONLY ONE ALLELE 	R63C12


# Analysis on unknown
```{r}

# Using quasi binomial log model

unknown_mod <- glm(cbind(number_of_GFP_kernels, number_of_WT_kernels) ~
                                as.factor(allele),
                              data = unknown,
                              family = quasibinomial(link = "logit"))
print(unknown_mod)

S = vcov(unknown_mod)

raw_p = coef(summary(unknown_mod))[1,4]
beta_list = coef(summary(unknown_mod))[1,1]
est_coef = (exp(beta_list)/(1 + exp(beta_list)))
low_int = exp(beta_list - qnorm(.975)*coef(summary(unknown_mod))[1,2])/(1+exp(beta_list - qnorm(.975)*coef(summary(unknown_mod))[1,2]))
up_int = exp(beta_list + qnorm(.975)*coef(summary(unknown_mod))[1,2])/(1+exp(beta_list + qnorm(.975)*coef(summary(unknown_mod))[1,2]))

for (i in 2:nrow(coef(summary(unknown_mod)))){ # Starting at 2 because we already collected the first one...
  beta = coef(summary(unknown_mod))[1,1] + coef(summary(unknown_mod))[i,1] # Intercept + Allele coefficient 
  sigma = sqrt(sum(S[c(1,i),c(1,i)])) # Sigma from variance matrix
  raw_p = c(raw_p, 2*(1-pnorm(abs(beta/sigma)))) # Raw p calculated using z normal distribution
  beta_list = c(beta_list, beta)
  est_coef = c(est_coef, (exp(beta)/(1+exp(beta))))
  low_int = c(low_int, exp(beta-qnorm(.975)*sigma)/(1+exp(beta-qnorm(.975)*sigma)))
  up_int = c(up_int, exp(beta+qnorm(.975)*sigma)/(1+exp(beta+qnorm(.975)*sigma)))
  
}

adjusted_p = p.adjust(raw_p, method = "BH")

Alleles = sort(unique(unknown$allele))

names(raw_p) = sort(unique(unknown$allele)) # Names is name or row, unique only picks unique value from dataset
names(beta_list) = sort(unique(unknown$allele))
names(est_coef) = sort(unique(unknown$allele))
names(Alleles) = sort(unique(unknown$allele))
names(adjusted_p) = sort(unique(unknown$allele))
names(low_int) = sort(unique(unknown$allele))
names(up_int) = sort(unique(unknown$allele))

nanalysis_summary_unknown = data.frame(allele = Alleles, logit_of_percentage = beta_list, estimated_transmission_percentage = est_coef, lower_confidence_interval = low_int, upper_confidence_interval = up_int, raw_p_value = raw_p, adj_p_value = adjusted_p)

nanalysis_summary_unknown$expression_category = "Unknown"
```


```{r}
nanalysis_summary = rbind(nanalysis_summary_vc, nanalysis_summary_sc)
nanalysis_summary = rbind(nanalysis_summary, nanalysis_summary_sc_n)
nanalysis_summary = rbind(nanalysis_summary, nanalysis_summary_vc_n)
nanalysis_summary = rbind(nanalysis_summary, nanalysis_summary_seed)
nanalysis_summary = rbind(nanalysis_summary, nanalysis_summary_unknown)

#write.table(nanalysis_summary, "clipboard", sep = "\t")
# Mac doesn't have clipboard manager

write.table(nanalysis_summary, file = "2023_analysis_sum.tsv", sep = "\t", row.names=FALSE) 
```

# Analysis on full mode 
```{r}

# Using quasi binomial log model

full_mod <- glm(cbind(number_of_GFP_kernels, number_of_WT_kernels) ~
                                as.factor(allele),
                              data = new_df,
                              family = quasibinomial(link = "logit"))
print(full_mod)

S = vcov(full_mod)

raw_p = coef(summary(full_mod))[1,4]
beta_list = coef(summary(full_mod))[1,1]
est_coef = (exp(beta_list)/(1 + exp(beta_list)))
low_int = exp(beta_list - qnorm(.975)*coef(summary(full_mod))[1,2])/(1+exp(beta_list - qnorm(.975)*coef(summary(full_mod))[1,2]))
up_int = exp(beta_list + qnorm(.975)*coef(summary(full_mod))[1,2])/(1+exp(beta_list + qnorm(.975)*coef(summary(full_mod))[1,2]))

for (i in 2:nrow(coef(summary(full_mod)))){ # Starting at 2 because we already collected the first one...
  beta = coef(summary(full_mod))[1,1] + coef(summary(full_mod))[i,1] # Intercept + Allele coefficient 
  sigma = sqrt(sum(S[c(1,i),c(1,i)])) # Sigma from variance matrix
  raw_p = c(raw_p, 2*(1-pnorm(abs(beta/sigma)))) # Raw p calculated using z normal distribution
  beta_list = c(beta_list, beta)
  est_coef = c(est_coef, (exp(beta)/(1+exp(beta))))
  low_int = c(low_int, exp(beta-qnorm(.975)*sigma)/(1+exp(beta-qnorm(.975)*sigma)))
  up_int = c(up_int, exp(beta+qnorm(.975)*sigma)/(1+exp(beta+qnorm(.975)*sigma)))
  
}

adjusted_p = p.adjust(raw_p, method = "BH")

Alleles = sort(unique(new_df$allele))

names(raw_p) = sort(unique(new_df$allele)) # Names is name or row, unique only picks unique value from dataset
names(beta_list) = sort(unique(new_df$allele))
names(est_coef) = sort(unique(new_df$allele))
names(Alleles) = sort(unique(new_df$allele))
names(adjusted_p) = sort(unique(new_df$allele))
names(low_int) = sort(unique(new_df$allele))
names(up_int) = sort(unique(new_df$allele))

nanalysis_summary_full = data.frame(allele = Alleles, logit_of_percentage = beta_list, estimated_transmission_percentage = est_coef, lower_confidence_interval = low_int, upper_confidence_interval = up_int, raw_p_value = raw_p, adj_p_value = adjusted_p)

```

```{r}
write.table(nanalysis_summary_full, file = "2023_noEC_analysis_sum.tsv", sep = "\t", row.names=FALSE) 
```


